# Generated by Django 4.2.6 on 2023-12-20 21:09

import app1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_studentdetail_reference_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetail',
            name='Reference_id',
            field=models.CharField(default=app1.models.generate_uuid, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
    ]
